version: '3'

services:
  front:
    container_name: 'front-app'
    build:
      context: ./front-app
      dockerfile: Dockerfile
    volumes:
      - ./front-app:/usr/src/app
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    environment:
     - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
